services:
  master:
    build: .
    container_name: hadoop-master
    hostname: master
    volumes:
      - hadoop_data:/data
    ports:
      - "9870:9870"  # HDFS Web UI
      - "8088:8088"  # YARN Web UI
    networks:
      - hadoop-net

  worker:
    build: .
    container_name: hadoop-worker-1
    hostname: worker-1
    volumes:
      - hadoop_data:/data
    networks:
      - hadoop-net

  worker_2:
    build: .
    container_name: hadoop-worker-2
    hostname: worker-2
    volumes:
      - hadoop_data:/data
    networks:
      - hadoop-net

  worker_3:
    build: .
    container_name: hadoop-worker-3
    hostname: worker-3
    volumes:
      - hadoop_data:/data
    networks:
      - hadoop-net

volumes:
  hadoop_data:

networks:
  hadoop-net: